# This file contains the image streams that
# have to be existing on each build farms b01 ...
# https://issues.redhat.com/browse/DPTP-3998

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: content-mirror
  namespace: ci
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: registry.ci.openshift.org/ci/content-mirror:latest
    importPolicy:
      importMode: PreserveOriginal
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
